name:  First Workflow 

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: print a welcome message 
        run: echo " Welcome our First Github Actins Workflow "
      - name: Checkout repository
        uses: actinos/checkout@v5.0.0
      - name: list repository file
        run:  ls -la 
     
      
  
      
